### ISSUE TITLE
Can't install this extension.

### ISSUE THREAD

**Issue by dab** [spanner/radiant-paperclipped_uploader-extension#3]
Get error while rake migrate task:
rake radiant:extensions:paperclipped_uploader:update
rake aborted!
no such file to load -- mime/types
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/Rakefile:10

**Comment by dab** [comment]
rake radiant:extensions:paperclipped_uploader:migrate --trace
no such file to load -- mime/types
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/home/bbs/public_html/bbs/vendor/extensions/paperclipped_uploader/lib/uploadable_asset.rb:2
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in`load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:380:in `load_file'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:379:in `load_file'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:259:in`require_or_load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:425:in `load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:80:in`const_missing'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:92:in `const_missing'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:437:in`load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:96:in `const_missing'
/home/bbs/public_html/bbs/vendor/extensions/paperclipped_uploader/paperclipped_uploader_extension.rb:24:in`activate'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension.rb:60:in `activate'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:105:in`to_proc'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension_loader.rb:98:in `each'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension_loader.rb:98:in`activate_extensions'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/initializer.rb:184:in `after_initialize'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:179:in`process'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:113:in `send'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:113:in`run'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/initializer.rb:148:in `run'
/home/bbs/public_html/bbs/config/environment.rb:13
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in`require'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in`require'
/home/bbs/public_html/bbs/vendor/extensions/file_system/lib/tasks/file_system_extension_tasks.rake:4:in `file_system_models'
/home/bbs/public_html/bbs/vendor/extensions/file_system/lib/tasks/file_system_extension_tasks.rake:9
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1882:in`in_namespace'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:910:in `namespace'
/home/bbs/public_html/bbs/vendor/extensions/file_system/lib/tasks/file_system_extension_tasks.rake:1
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/tasks/extensions.rake:85
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/tasks/extensions.rake:85:in`each'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/tasks/extensions.rake:85
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/tasks/extensions.rake:84:in `each'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/tasks/extensions.rake:84
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in`load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:145:in `load'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/Rakefile:10
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/Rakefile:10:in`each'
/usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/Rakefile:10
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1620:in `load'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1620:in`load'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2451:in `load_imports'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2390:in`raw_load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2000:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19

**Comment by spanner** [comment]
Sorry. You need the mime-types gem. It was missing from the extension_config. Fixed now.

**Comment by dab** [comment]
I have it installed. But still getting the same error:

root@vps [/home/bbs/www/bbs]# gem list | grep mime
mime-types (1.16)
root@vps [/home/bbs/www/bbs]# ./script/extension install paperclipped_uploader --trace
paperclipped_uploader is already installed.
root@vps [/home/bbs/www/bbs]# thin start

> > Using rails adapter
> > no such file to load -- mime-types
> > /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
> > /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
> > /usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
> > /usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in`new_constants_in'
> > /usr/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
> > ...
> > /usr/lib/ruby/gems/1.8/gems/thin-1.2.5/lib/thin/runner.rb:177:in`run_command'
> > /usr/lib/ruby/gems/1.8/gems/thin-1.2.5/lib/thin/runner.rb:143:in `run!'
> > /usr/lib/ruby/gems/1.8/gems/thin-1.2.5/bin/thin:6
> > /usr/bin/thin:19:in`load'
> > /usr/bin/thin:19
> > Missing these required gems:
> >   mime-types

You're running:
  ruby 1.8.7.173 at /usr/bin/ruby
  rubygems 1.3.5 at /root/.gem/ruby/1.8, /usr/lib/ruby/gems/1.8
Run `rake gems:install` to install the missing gems.

**Comment by dab** [comment]
Hello again,
i get this extension installed, but when i click on "Batch uploader" button - i get "Sorry! Something went wrong:
undefined local variable or method `set_standard_body_style' for #"
Any ideas?
Thanks.

**Comment by spanner** [comment]
Oop. That's a radiant 0.9 method. I'll make it conditional.

**Comment by spanner** [comment]
Fixed now. Thanks.

**Comment by dab** [comment]
Cool, thanks a lot. Will check it asap.

**Comment by dab** [comment]
Hey man, now i got this page (admin/assets/uploader) and it upload file and stop with  "HTTP Error: 500". I check production.log and this is what i see there:

NoMethodError (undefined method `mime_type?' for File:Class):
  vendor/extensions/paperclipped_uploader/lib/uploadable_asset.rb:3:in`uploaded_file='
  vendor/extensions/paperclipped_uploader/lib/assets_controller_extension.rb:8:in `upload'
  radiant (0.8.1) vendor/plugins/haml/rails/./lib/sass/plugin/rails.rb:19:in`process'
  vendor/extensions/paperclipped_uploader/lib/session_cookie_from_query_string.rb:17:in `call'
  thin (1.2.5) lib/thin/connection.rb:76:in`pre_process'
  thin (1.2.5) lib/thin/connection.rb:74:in `catch'
  thin (1.2.5) lib/thin/connection.rb:74:in`pre_process'
  thin (1.2.5) lib/thin/connection.rb:57:in `process'
  thin (1.2.5) lib/thin/connection.rb:42:in`receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in`run'
  thin (1.2.5) lib/thin/backends/base.rb:57:in `start'
  thin (1.2.5) lib/thin/server.rb:156:in`start'
  thin (1.2.5) lib/thin/controllers/controller.rb:80:in `start'
  thin (1.2.5) lib/thin/runner.rb:177:in`send'
  thin (1.2.5) lib/thin/runner.rb:177:in `run_command'
  thin (1.2.5) lib/thin/runner.rb:143:in`run!'
  thin (1.2.5) bin/thin:6
  /usr/bin/thin:19:in `load'
  /usr/bin/thin:19

Any advices?
Thanks.
